require 'rspec/core/rake_task'

task :test do
  Rake::Task['spec:test'].invoke
end

namespace :spec do
  RSpec::Core::RakeTask.new(:test) do |t|
    t.pattern = %w{ spec/**/*_spec.rb}
  end
end

task default: :test

desc 'Build gem into the pkg directory'
task :build do
  FileUtils.rm_rf('pkg')
  Dir['*.gemspec'].each do |gemspec|
    system "gem build #{gemspec}"
  end
  FileUtils.mkdir_p('pkg')
  FileUtils.mv(Dir['*.gem'], 'pkg')
end
