source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'
gem 'sidekiq'

gem 'mst-status', :path => '../mst-status'
gem 'mst-status-sidekiq', :path => '../mst-status'

group :development do
  gem 'rspec'
  gem 'rspec-mocks'
end
